using System.Collections.Generic;

namespace SP.Core
{
    // Textos del tutorial y de la mision en ingles (item 27). Loc los suma a su tabla al iniciar; la clave es el texto
    // original en espanol tal como aparece en pantalla. Los textos con datos vivos (contadores, distancias) siguen en
    // espanol porque cambian a cada frame y no tienen una clave fija.
    public static class LocTextos
    {
        public static readonly Dictionary<string, string> Tutorial = new Dictionary<string, string>
        {
            { "MOVER LA CÁMARA", "MOVE THE CAMERA" },
            { "Mira a los costados (izquierda y derecha)", "Look to the sides (left and right)" },
            { "Mueve el MOUSE hacia los costados para girar la cámara.", "Move the MOUSE sideways to turn the camera." },
            { "Si la cámara no gira, haz clic dentro de la ventana del juego.", "If the camera does not turn, click inside the game window." },
            { "Mira arriba y abajo", "Look up and down" },
            { "Ahora mueve el MOUSE hacia arriba y hacia abajo.", "Now move the MOUSE up and down." },
            { "Sube y baja el mouse: la mira sigue tu mano.", "Move the mouse up and down: the crosshair follows your hand." },
            { "MOVERSE CON W A S D", "MOVE WITH W A S D" },
            { "W · adelante", "W · forward" },
            { "A · izquierda", "A · left" },
            { "S · atrás", "S · back" },
            { "D · derecha", "D · right" },
            { "CORRER CON SHIFT", "RUN WITH SHIFT" },
            { "Mantén SHIFT y camina adelante (W)", "Hold SHIFT and walk forward (W)" },
            { "Mantén SHIFT mientras caminas hacia adelante con W: corres, las piernas se aceleran y tus aliados corren contigo.", "Hold SHIFT while walking forward with W: you run, your legs speed up and your allies run with you." },
            { "SHIFT izquierdo y W a la vez. No sirve agachado ni apuntando.", "Left SHIFT and W together. It does not work crouched or aiming." },
            { "Suelta SHIFT: vuelves a caminar", "Release SHIFT: you walk again" },
            { "Suelta SHIFT: vuelves al paso normal.", "Release SHIFT: back to a normal pace." },
            { "Deja de apretar SHIFT sin dejar de caminar.", "Stop pressing SHIFT without stopping walking." },
            { "Elimina al enemigo quieto (rojo)", "Take out the standing enemy (red)" },
            { "Apunta la mira al ENEMIGO ROJO y dispara con el CLIC IZQUIERDO (mantenlo para ráfaga).", "Aim at the RED ENEMY and fire with the LEFT CLICK (hold it for a burst)." },
            { "Lleva el punto de la mira sobre el soldado. Si no hay balas, recarga con R.", "Put the crosshair dot on the soldier. If you are out of bullets, reload with R." },
            { "Dispara a la pared gris", "Shoot the gray wall" },
            { "Ahora dispara a la PARED GRIS: la bala levanta cubitos amarillos y no la rompe.", "Now shoot the GRAY WALL: the bullet kicks up yellow cubes and does not break it." },
            { "La pared gris es indestructible: solo comprueba el impacto.", "The gray wall is indestructible: it only checks the impact." },
            { "Destruye la caja amarilla", "Destroy the yellow crate" },
            { "Dispara a la CAJA AMARILLA hasta destruirla: cada impacto la daña.", "Shoot the YELLOW CRATE until it is destroyed: every hit damages it." },
            { "Sigue disparando a la caja hasta que se derrumbe.", "Keep shooting the crate until it collapses." },
            { "ENEMIGO QUIETO", "STANDING ENEMY" },
            { "PARED (no se rompe)", "WALL (unbreakable)" },
            { "CAJA DESTRUCTIBLE", "DESTRUCTIBLE CRATE" },
            { "CAMBIAR DE SOLDADO (RADIAL)", "SWITCH SOLDIER (RADIAL)" },
            { "Mantén Q: se abre el radial de órdenes", "Hold Q: the orders radial opens" },
            { "Mantén apretada la tecla [Q]: se abre el RADIAL. Siempre ofrece IR ALLÍ, CUBRIRSE y POSICIÓN; lo demás aparece en DORADO solo si apuntas a algo con lo que se puede interactuar.", "Hold the [Q] key: the RADIAL opens. It always offers GO THERE, COVER and POSITION; the rest shows in GOLD only if you aim at something you can interact with." },
            { "Mantén Q sin soltarla. Un TOQUE corto de Q hace otra cosa: ejecuta al instante la acción rápida de lo que miras (ATACAR al enemigo, CURAR/REANIMAR al herido o caído, que un aliado te SIGA).", "Hold Q without releasing it. A short TAP of Q does something else: it instantly runs the quick action for what you are aiming at (ATTACK the enemy, HEAL/REVIVE the wounded or fallen, make an ally FOLLOW you)." },
            { "Apunta a un aliado → Q → POSEER (dorado)", "Aim at an ally → Q → POSSESS (gold)" },
            { "MIRA a un aliado (columna celeste) y mantén [Q]: arriba aparece POSEER en dorado. Mueve el mouse hacia ARRIBA (POSEER), sigue hacia AFUERA hasta POSEER A ESTE y suelta Q: tomas su control.", "LOOK at an ally (light-blue column) and hold [Q]: POSSESS shows up in gold at the top. Move the mouse UP (POSSESS), keep going OUT to POSSESS THIS ONE and release Q: you take control." },
            { "Primero deja al aliado en el centro de la mira; recién después mantén Q (la mira se congela al abrirse).", "First put the ally in the center of the crosshair; only then hold Q (the aim freezes when it opens)." },
            { "Mantén CTRL: te agachas", "Hold CTRL: you crouch" },
            { "Mantén apretada la tecla CTRL: tu soldado se agacha (menos visible y más preciso).", "Hold the CTRL key: your soldier crouches (less visible and more accurate)." },
            { "Es la tecla Ctrl de la izquierda del teclado.", "It is the Ctrl key on the left of the keyboard." },
            { "Suelta CTRL: te levantas", "Release CTRL: you stand up" },
            { "Suelta CTRL para volver a ponerte de pie.", "Release CTRL to stand up again." },
            { "Basta con dejar de apretar Ctrl.", "Just stop pressing Ctrl." },
            { "SALTAR", "JUMP" },
            { "ESPACIO: saltas", "SPACE: you jump" },
            { "Aprieta la barra ESPACIADORA: tu soldado salta. Mira el cuerpo: las piernas se recogen en el aire y no se hunde en el piso.", "Press the SPACE BAR: your soldier jumps. Watch the body: the legs tuck in the air and it does not sink into the floor." },
            { "Barra espaciadora. No se puede saltar agachado ni desde la torreta.", "Space bar. You cannot jump while crouched or from the turret." },
            { "Espera a caer: al tocar el piso suena el golpe y la cámara se sacude un poco.", "Wait to land: on touching the floor you hear the thud and the camera shakes a little." },
            { "Cae solo, no hace falta apretar nada.", "You land by yourself, no need to press anything." },
            { "APUNTAR: MIRA EN PRIMERA PERSONA", "AIM: FIRST-PERSON SIGHT" },
            { "Mantén el CLIC DERECHO: apuntas", "Hold the RIGHT CLICK: you aim" },
            { "Mantén apretado el CLIC DERECHO: apuntas con la mira del arma y la cámara hace zoom.", "Hold the RIGHT CLICK: you aim down the weapon sight and the camera zooms." },
            { "Mantén el botón derecho del mouse apretado (no lo sueltes todavía).", "Keep the right mouse button held (do not release it yet)." },
            { "La cámara pasa a los OJOS del soldado", "The camera moves to the soldier's EYES" },
            { "Sin soltar: la cámara viaja de encima del hombro a los ojos del soldado (primera persona). Fíjate cómo la mira respira.", "Without releasing: the camera travels from over the shoulder to the soldier's eyes (first person). Notice how the sight breathes." },
            { "Sigue manteniendo el clic derecho un segundo más.", "Keep holding the right click one more second." },
            { "Dispara mientras apuntas", "Fire while aiming" },
            { "Sin soltar el clic derecho, dispara con el CLIC IZQUIERDO.", "Without releasing the right click, fire with the LEFT CLICK." },
            { "Con el derecho apretado, clic izquierdo para disparar.", "With the right held, left click to fire." },
            { "Suelta: vuelve el encuadre normal", "Release: the normal framing returns" },
            { "Suelta el clic derecho: la cámara vuelve a verte por encima del hombro.", "Release the right click: the camera goes back to an over-the-shoulder view." },
            { "Basta con soltar el botón derecho.", "Just release the right button." },
            { "ARMAS: MIRA Y SONIDO PROPIOS", "WEAPONS: OWN SIGHT AND SOUND" },
            { "1 / 2 / 3 o rueda: cambias de arma", "1 / 2 / 3 or wheel: you swap weapons" },
            { "Cambia de arma con [1] [2] [3] (o la rueda del mouse). Cada arma suena distinto al sacarla, al disparar y al recargar, y tiene su PROPIA MIRA (cruz, punto, anillo, chevrón, mildot...).", "Swap weapons with [1] [2] [3] (or the mouse wheel). Each weapon sounds different when drawn, fired and reloaded, and has its OWN SIGHT (cross, dot, ring, chevron, mil-dot...)." },
            { "Aprieta 2 o 3 (o gira la rueda del mouse).", "Press 2 or 3 (or turn the mouse wheel)." },
            { "Dispara y recarga con R", "Fire and reload with R" },
            { "Dispara unas balas y aprieta [R]: cada arma recarga con su propia secuencia (cargador, cerrojo, cartuchos, tapa de la caja...) y avisa RECARGANDO.", "Fire a few bullets and press [R]: each weapon reloads with its own sequence (magazine, bolt, shells, box cover...) and shows RELOADING." },
            { "Primero gasta una bala con el clic izquierdo: con el cargador lleno no recarga.", "First spend a bullet with the left click: with a full magazine it does not reload." },
            { "Apunta con la otra arma: otra mira", "Aim with the other weapon: a different sight" },
            { "Mantén el CLIC DERECHO con esta arma: la retícula de la mira es distinta a la anterior.", "Hold the RIGHT CLICK with this weapon: the sight reticle is different from the previous one." },
            { "Clic derecho mantenido con el arma que acabas de elegir.", "Right click held with the weapon you just picked." },
            { "CUCHILLO", "KNIFE" },
            { "F: das un tajo", "F: you slash" },
            { "Aprieta [F]: tu soldado saca el cuchillo y da un tajo (arco brillante y silbido). No gasta balas y funciona con cualquier arma.", "Press [F]: your soldier draws the knife and slashes (bright arc and whoosh). It uses no bullets and works with any weapon." },
            { "Tecla F. Tiene una pequeña espera entre tajos.", "F key. There is a short wait between slashes." },
            { "Acércate al enemigo y apuñálalo", "Get close to the enemy and stab him" },
            { "Camina hasta el ENEMIGO ROJO (a 2 m o menos) y dale un tajo con [F]: golpe sordo, chispa roja y sacudida.", "Walk up to the RED ENEMY (2 m or less) and slash with [F]: dull thud, red spark and shake." },
            { "El cuchillo llega a 2 m. Acércate de frente al enemigo.", "The knife reaches 2 m. Approach the enemy from the front." },
            { "Derríbalo con el cuchillo", "Take him down with the knife" },
            { "Sigue dándole tajos con [F] hasta derribarlo.", "Keep slashing with [F] until he falls." },
            { "Cada cuchillada le quita más de la mitad de la vida a un enemigo normal.", "Each stab takes more than half the health of a normal enemy." },
            { "ENEMIGO · CUCHILLO [F]", "ENEMY · KNIFE [F]" },
            { "GRANADA", "GRENADE" },
            { "Mantén G: se dibuja la curva", "Hold G: the arc is drawn" },
            { "Mantén apretada la tecla [G]: aparece la CURVA exacta de la granada y un anillo con el radio de la explosión donde va a caer. Apunta al enemigo rojo.", "Hold the [G] key: the exact grenade ARC appears, with a ring showing the blast radius where it will land. Aim at the red enemy." },
            { "Mantén G sin soltarla. Baja un poco la mira si cae corto.", "Hold G without releasing. Lower the aim a little if it falls short." },
            { "Suelta G: la lanzas", "Release G: you throw it" },
            { "Con el anillo sobre el enemigo, SUELTA [G]: la granada sale, rebota si choca y suena el tic-tac del fusible. (Clic derecho o Esc: la guardas.)", "With the ring on the enemy, RELEASE [G]: the grenade flies, bounces if it hits something and the fuse ticks. (Right click or Esc: put it away.)" },
            { "Suelta la tecla G.", "Release the G key." },
            { "Explota: estruendo y onda", "It explodes: boom and shockwave" },
            { "Espera 2 segundos y medio: explota con estruendo, sacudida y daño con caída hacia el borde del anillo. No lastima a tu bando.", "Wait two and a half seconds: it explodes with a boom, shake and damage that falls off toward the ring edge. It does not hurt your side." },
            { "Aléjate del anillo si lanzaste cerca de ti (tu bando no recibe daño, pero la onda empuja).", "Move away from the ring if you threw it close to you (your side takes no damage, but the blast pushes)." },
            { "BLANCO · GRANADA [G]", "TARGET · GRENADE [G]" },
            { "CAJA DE SUMINISTROS", "SUPPLY CRATE" },
            { "Camina hasta la caja verde", "Walk to the green crate" },
            { "Ya gastaste granadas y perdiste vida. En la misión hay CAJAS DE SUMINISTROS (verdes, con cruz blanca, flotan y giran). Camina hasta la que tienes delante: te repone las 3 granadas y cura el 60 % de la vida. Se vuelve a llenar a los 45 segundos.", "You have used grenades and lost health. In the mission there are SUPPLY CRATES (green, with a white cross, floating and spinning). Walk to the one in front of you: it restocks your 3 grenades and heals 60 % of your health. It refills after 45 seconds." },
            { "Camina hacia la caja hasta tocarla.", "Walk to the crate until you touch it." },
            { "VER COBERTURAS Y RUTAS", "SEE COVER AND ROUTES" },
            { "Mantén C: aparecen las coberturas", "Hold C: cover points appear" },
            { "Mantén apretada la tecla [C]: los puntos de cobertura del piso (discos celestes) y las rutas de patrulla enemigas se hacen visibles. Soltando la tecla se esconden.", "Hold the [C] key: the floor cover points (light-blue discs) and the enemy patrol routes become visible. Releasing the key hides them." },
            { "La tecla C está entre la X y la V.", "The C key is between X and V." },
            { "Suelta C: se esconden", "Release C: they hide" },
            { "Suelta la tecla [C]: el mapa vuelve a quedar limpio. (Con el radial sobre CUBRIRSE también se ven.)", "Release the [C] key: the map is clean again. (They also show with the radial on COVER.)" },
            { "Deja de apretar C.", "Stop pressing C." },
            { "RTS: ORDEN A LOS 2", "RTS: ORDER THE 2" },
            { "TAB: pasa a la vista táctica (RTS)", "TAB: switch to the tactical view (RTS)" },
            { "Presiona [TAB]: la cámara sube y ves el mapa desde arriba.", "Press [TAB]: the camera rises and you see the map from above." },
            { "TAB está encima de Bloq Mayús.", "TAB is above Caps Lock." },
            { "Selecciona a los 2 aliados", "Select the 2 allies" },
            { "Arrastra un recuadro con el CLIC IZQUIERDO alrededor de tus 2 aliados (columnas celestes), o Ctrl+A. Rueda del mouse: zoom hacia donde apuntas con el cursor.", "Drag a box with the LEFT CLICK around your 2 allies (light-blue columns), or Ctrl+A. Mouse wheel: zoom toward the cursor." },
            { "Mantén el clic izquierdo y arrastra un recuadro que los incluya a los dos.", "Hold the left click and drag a box that includes both." },
            { "CLIC DERECHO en el círculo verde: van ahí", "RIGHT CLICK on the green circle: they go there" },
            { "Clic DERECHO sobre el CÍRCULO VERDE: los 2 aliados caminan hasta allí. (Rueda del mouse: zoom hacia el cursor.)", "RIGHT click on the GREEN CIRCLE: the 2 allies walk there. (Mouse wheel: zoom toward the cursor.)" },
            { "Apunta al círculo verde y clic derecho. Cerca del círculo alcanza.", "Aim at the green circle and right click. Near the circle is enough." },
            { "ZONA A · clic derecho", "ZONE A · right click" },
            { "VOLVER A PRIMERA PERSONA", "BACK TO FIRST PERSON" },
            { "TAB: vuelves a primera persona (FPS)", "TAB: back to first person (FPS)" },
            { "Presiona [TAB] otra vez para volver a mirar por los ojos de tu soldado.", "Press [TAB] again to look through your soldier's eyes." },
            { "TAB alterna entre la vista táctica y la primera persona.", "TAB toggles between the tactical view and first person." },
            { "Clic izquierdo: el mouse vuelve a la cámara", "Left click: the mouse controls the camera again" },
            { "Haz un CLIC IZQUIERDO en la pantalla: el mouse vuelve a controlar la cámara.", "Make a LEFT CLICK on the screen: the mouse controls the camera again." },
            { "Hace falta un clic para capturar el mouse otra vez.", "One click is needed to capture the mouse again." },
            { "SÍGANME Y QUIETOS (RADIAL)", "FOLLOW ME AND HOLD (RADIAL)" },
            { "Q → POSICIÓN → SÍGANME", "Q → POSITION → FOLLOW ME" },
            { "Mantén [Q], elige POSICIÓN (siempre está) y sigue hacia AFUERA hasta SÍGANME (la pista celeste late). Suelta Q: los 2 aliados vienen hacia ti.", "Hold [Q], pick POSITION (always there) and keep going OUT to FOLLOW ME (the light-blue hint pulses). Release Q: the 2 allies come to you." },
            { "POSICIÓN; SÍGANME es la segunda opción del anillo de afuera.", "POSITION; FOLLOW ME is the second option of the outer ring." },
            { "Los 2 aliados te siguen", "The 2 allies follow you" },
            { "Mira cómo vienen: cada aliado que te sigue lo marca el ícono verde.", "Watch them come: each ally following you is marked with the green icon." },
            { "Espera unos segundos: caminan hacia ti.", "Wait a few seconds: they walk to you." },
            { "Q → POSICIÓN → TODOS QUIETOS", "Q → POSITION → ALL HOLD" },
            { "Ahora que se queden: [Q], POSICIÓN y TODOS QUIETOS (la primera opción). Se plantan donde están y ya no te siguen.", "Now make them stay: [Q], POSITION and ALL HOLD (the first option). They plant where they are and stop following you." },
            { "Es la primera opción de POSICIÓN.", "It is the first option of POSITION." },
            { "SELECCIONAR EN FPS", "SELECT IN FPS" },
            { "SHIFT + CLIC DERECHO sobre un aliado", "SHIFT + RIGHT CLICK on an ally" },
            { "Tus aliados se adelantaron. Mira a uno, mantén SHIFT y haz CLIC DERECHO sobre él: queda seleccionado.", "Your allies moved ahead. Look at one, hold SHIFT and RIGHT CLICK on him: he gets selected." },
            { "Gira el mouse hasta tener a un aliado en la mira (están unos 9 metros delante).", "Turn the mouse until an ally is in your crosshair (they are about 9 meters ahead)." },
            { "ORDEN DE MOVER EN FPS", "MOVE ORDER IN FPS" },
            { "CLIC DERECHO en el suelo: el aliado va", "RIGHT CLICK on the ground: the ally goes" },
            { "Con el aliado seleccionado, haz CLIC DERECHO en el SUELO: caminará hasta allí.", "With the ally selected, RIGHT CLICK on the GROUND: he will walk there." },
            { "Apunta al piso (no a una pared) y clic derecho.", "Aim at the floor (not a wall) and right click." },
            { "ORDEN AQUÍ", "ORDER HERE" },
            { "IR ALLÍ Y ATACAR (RADIAL)", "GO THERE AND ATTACK (RADIAL)" },
            { "Q → IR ALLÍ → TODOS", "Q → GO THERE → ALL" },
            { "Mira al SUELO donde quieres que vayan (círculo verde) y mantén [Q]: IR ALLÍ está siempre. Elige TODOS: los 2 aliados caminan hasta el punto que apuntabas.", "Look at the GROUND where you want them to go (green circle) and hold [Q]: GO THERE is always available. Pick ALL: the 2 allies walk to the point you aimed at." },
            { "IR ALLÍ es la primera categoría; TODOS la primera opción. Apunta al piso antes de mantener Q.", "GO THERE is the first category; ALL the first option. Aim at the floor before holding Q." },
            { "Apunta al enemigo → Q → ATACAR (dorado)", "Aim at the enemy → Q → ATTACK (gold)" },
            { "Ahora mira al ENEMIGO ROJO y mantén [Q]: ATACAR aparece en dorado. Elige TODOS: tus aliados le disparan.", "Now look at the RED ENEMY and hold [Q]: ATTACK shows in gold. Pick ALL: your allies fire at him." },
            { "Deja al enemigo rojo en el centro de la mira antes de mantener Q.", "Put the red enemy in the center of the crosshair before holding Q." },
            { "Tus aliados lo derriban", "Your allies take him down" },
            { "Mira cómo se paran a disparar. Espera a que caiga.", "Watch them stop and fire. Wait for him to fall." },
            { "Tardan un par de segundos en verlo y apuntar.", "They take a couple of seconds to see him and aim." },
            { "ENEMIGO · ATACAR", "ENEMY · ATTACK" },
            { "IR ALLÍ", "GO THERE" },
            { "FORMACIONES Y RETIRADA (RADIAL)", "FORMATIONS AND RETREAT (RADIAL)" },
            { "Q → POSICIÓN → FORMAR LÍNEA", "Q → POSITION → FORM LINE" },
            { "Mantén [Q], elige POSICIÓN y sigue hasta FORMAR LÍNEA: los aliados se colocan uno al lado del otro, de cara hacia donde miras.", "Hold [Q], pick POSITION and keep going to FORM LINE: the allies line up side by side, facing where you look." },
            { "POSICIÓN; FORMAR LÍNEA es la tercera opción del anillo de afuera.", "POSITION; FORM LINE is the third option of the outer ring." },
            { "Q → POSICIÓN → FORMAR CUÑA", "Q → POSITION → FORM WEDGE" },
            { "Ahora FORMAR CUÑA (la cuarta opción): forman una V con la punta hacia adelante.", "Now FORM WEDGE (the fourth option): they form a V with the point forward." },
            { "POSICIÓN; FORMAR CUÑA está justo a continuación de FORMAR LÍNEA.", "POSITION; FORM WEDGE comes right after FORM LINE." },
            { "Q → POSICIÓN → RETIRADA", "Q → POSITION → RETREAT" },
            { "Por último RETIRADA (la última opción): los aliados vuelven hacia ti a cubierto.", "Finally RETREAT (the last option): the allies come back to you under cover." },
            { "POSICIÓN; RETIRADA es la última opción.", "POSITION; RETREAT is the last option." },
            { "CUBRIRSE HACIA DONDE MIRO (RADIAL)", "TAKE COVER WHERE I LOOK (RADIAL)" },
            { "Q → CUBRIRSE → TODOS", "Q → COVER → ALL" },
            { "Mira hacia las 2 coberturas de sacos (columnas naranjas). Mantén [Q], elige CUBRIRSE (los discos celestes de cobertura se ven mientras el radial está ahí) y sigue hasta TODOS: se ponen del lado protegido, lejos de donde miras.", "Look toward the 2 sandbag covers (orange columns). Hold [Q], pick COVER (the light-blue cover discs show while the radial is there) and keep going to ALL: they take the protected side, away from where you look." },
            { "CUBRIRSE; TODOS es la primera opción. Mira antes hacia los sacos.", "COVER; ALL is the first option. Look at the sandbags first." },
            { "Los 2 aliados quedan en cobertura", "The 2 allies take cover" },
            { "Espera: caminan, se agachan detrás de los sacos y quedan a cubierto.", "Wait: they walk, crouch behind the sandbags and stay covered." },
            { "Tardan unos segundos.", "They take a few seconds." },
            { "CURAR A UN ALIADO (RADIAL)", "HEAL AN ALLY (RADIAL)" },
            { "Apunta al herido → Q → CURAR (dorado)", "Aim at the wounded → Q → HEAL (gold)" },
            { "Un aliado está herido (columna roja, mira su barra abajo a la izquierda). MÍRALO y mantén [Q]: CURAR aparece en dorado arriba. Sigue hasta CURAR A ESTE: el médico va y lo atiende. (Solo aparece si apuntas a un herido y el médico vive.)", "An ally is wounded (red column, see his bar at the bottom left). LOOK at him and hold [Q]: HEAL shows in gold at the top. Keep going to HEAL THIS ONE: the medic goes and treats him. (It only shows if you aim at a wounded ally and the medic is alive.)" },
            { "Deja al herido en la mira antes de mantener Q.", "Put the wounded ally in the crosshair before holding Q." },
            { "El médico cura al herido", "The medic heals the wounded" },
            { "Espera: el médico llega junto al herido y le devuelve la vida.", "Wait: the medic reaches the wounded ally and restores his health." },
            { "El médico tiene que llegar a menos de 2,5 m.", "The medic has to get within 2.5 m." },
            { "REANIMAR A UN CAÍDO (RADIAL)", "REVIVE A FALLEN ALLY (RADIAL)" },
            { "Apunta al caído → Q → REANIMAR (dorado)", "Aim at the fallen → Q → REVIVE (gold)" },
            { "Un aliado CAYÓ (columna roja). MÍRALO y mantén [Q]: REANIMAR aparece en dorado (solo si queda un médico vivo). Elige REANIMAR A ESTE.", "An ally FELL (red column). LOOK at him and hold [Q]: REVIVE shows in gold (only if a medic is still alive). Pick REVIVE THIS ONE." },
            { "Deja al caído en la mira antes de mantener Q.", "Put the fallen ally in the crosshair before holding Q." },
            { "El médico lo levanta (4 s junto a él)", "The medic gets him up (4 s next to him)" },
            { "Espera: el médico corre hasta el caído, se queda a su lado 4 segundos y lo reanima.", "Wait: the medic runs to the fallen ally, stays beside him for 4 seconds and revives him." },
            { "CURARME (RADIAL)", "HEAL ME (RADIAL)" },
            { "Q → CURAR → CURARME (dorado)", "Q → HEAL → HEAL ME (gold)" },
            { "TÚ estás herido (barra roja abajo a la izquierda). Con la salud baja, CURAR aparece solo en el radial, sin apuntar a nadie. Mantén [Q], elige CURAR y CURARME: el médico viene por ti.", "YOU are wounded (red bar at the bottom left). With low health, HEAL shows in the radial on its own, without aiming at anyone. Hold [Q], pick HEAL and HEAL ME: the medic comes for you." },
            { "Con menos del 70% de vida aparece CURAR en dorado.", "With less than 70% health, HEAL shows in gold." },
            { "El médico te cura", "The medic heals you" },
            { "Quédate cerca: el médico llega, suena la campanita y recuperas la vida.", "Stay close: the medic arrives, the little bell rings and you recover health." },
            { "DEMOLER UN MURO (ASALTO)", "DEMOLISH A WALL (ASSAULT)" },
            { "Apunta al muro de práctica (columna naranja)", "Aim at the practice wall (orange column)" },
            { "Ahora eres el soldado de ASALTO: apunta al muro de práctica (a unos 5 m). Al apuntarlo, el radial [Q] ofrece DEMOLER en dorado. Solo el asalto puede demoler.", "You are now the ASSAULT soldier: aim at the practice wall (about 5 m away). When aimed at, the [Q] radial offers DEMOLISH in gold. Only the assault soldier can demolish." },
            { "Mira al bloque marcado con la columna naranja.", "Look at the block marked with the orange column." },
            { "Q → DEMOLER → YO DEMUELO", "Q → DEMOLISH → I DEMOLISH" },
            { "Manteniendo el muro en la mira, mantén [Q]: DEMOLER aparece en dorado. Elige YO DEMUELO (la segunda opción).", "Keeping the wall in your crosshair, hold [Q]: DEMOLISH shows in gold. Pick I DEMOLISH (the second option)." },
            { "DEMOLER solo aparece si apuntas al muro y eres el asalto.", "DEMOLISH only shows if you aim at the wall and are the assault soldier." },
            { "CTRL agachado y quieto: carga 4 s", "CTRL crouched and still: charge 4 s" },
            { "Mantén CTRL (agachado) y NO te muevas: aparece un anillo que se llena en 4 segundos y suenan los pitidos de la carga.", "Hold CTRL (crouched) and DO NOT move: a ring fills in 4 seconds and the charge beeps sound." },
            { "Si te levantas o te mueves, la carga se cancela.", "If you stand up or move, the charge is cancelled." },
            { "El muro vuela en pedazos", "The wall blows to pieces" },
            { "Sigue quieto hasta que el anillo se llene: la carga explota y el muro desaparece.", "Stay still until the ring fills: the charge explodes and the wall disappears." },
            { "Tarda 4 segundos seguidos, quieto y agachado.", "It takes 4 seconds in a row, still and crouched." },
            { "EL ASALTO ALIADO PONE LA BOMBA (RADIAL)", "THE ALLIED ASSAULT PLANTS THE BOMB (RADIAL)" },
            { "Q → DEMOLER → ASALTO DEMUELE", "Q → DEMOLISH → ASSAULT DEMOLISHES" },
            { "Ahora manejas a otro soldado y el ASALTO es tu aliado. Apunta al muro (a unos 24 m), mantén [Q] y elige ASALTO DEMUELE (la primera opción): tu aliado corre, se agacha y planta la carga.", "Now you control another soldier and the ASSAULT is your ally. Aim at the wall (about 24 m away), hold [Q] and pick ASSAULT DEMOLISHES (the first option): your ally runs, crouches and plants the charge." },
            { "DEMOLER en dorado; ASALTO DEMUELE es la primera opción.", "DEMOLISH in gold; ASSAULT DEMOLISHES is the first option." },
            { "Q → DEMOLER → CANCELAR (mientras va)", "Q → DEMOLISH → CANCEL (while he goes)" },
            { "Sin dejar de mirar el muro, mantén [Q] otra vez: DEMOLER ofrece CANCELAR (la última opción) mientras el asalto está yendo o plantando. Elígela: se detiene.", "Without looking away from the wall, hold [Q] again: DEMOLISH offers CANCEL (the last option) while the assault soldier is going or planting. Pick it: he stops." },
            { "Hay que hacerlo antes de que la carga llegue a 4 s. Mira el muro y usa el radial rápido.", "You must do it before the charge reaches 4 s. Look at the wall and use the radial quickly." },
            { "Otra vez ASALTO DEMUELE", "ASSAULT DEMOLISHES again" },
            { "Vuelve a elegir ASALTO DEMUELE. Esta vez no canceles.", "Pick ASSAULT DEMOLISHES again. Do not cancel this time." },
            { "Q, DEMOLER, ASALTO DEMUELE.", "Q, DEMOLISH, ASSAULT DEMOLISHES." },
            { "Espera 4 segundos: la carga explota (estruendo, onda y pitidos) y el muro desaparece.", "Wait 4 seconds: the charge explodes (boom, shockwave and beeps) and the wall disappears." },
            { "El asalto tiene que llegar, agacharse y quedarse quieto 4 s.", "The assault soldier has to arrive, crouch and stay still for 4 s." },
            { "AMETRALLADORA FIJA", "FIXED MACHINE GUN" },
            { "Acércate a la torreta amarilla (4 m)", "Get close to the yellow turret (4 m)" },
            { "Camina hasta la AMETRALLADORA FIJA marcada con la columna naranja. Es fija: no se lleva.", "Walk to the FIXED MACHINE GUN marked with the orange column. It is fixed: it cannot be carried." },
            { "Está unos 9 m delante de ti.", "It is about 9 m ahead of you." },
            { "Q → TORRETA FIJA → USAR", "Q → FIXED TURRET → USE" },
            { "Mírala y mantén [Q]: TORRETA FIJA aparece en dorado. Elige USAR LA TORRETA: te plantas detrás del arma. Solo giras dentro de un arco y no puedes caminar. (En este paso [E] está desactivado para que practiques el radial.)", "Look at it and hold [Q]: FIXED TURRET shows in gold. Pick USE THE TURRET: you plant yourself behind the gun. You only turn within an arc and cannot walk. (In this step [E] is disabled so you practice the radial.)" },
            { "Apunta a la torreta antes de mantener Q; el cartel dorado la marca.", "Aim at the turret before holding Q; the gold sign marks it." },
            { "Dispara una ráfaga", "Fire a burst" },
            { "Dispara con el CLIC IZQUIERDO: la cinta tiene 100 balas. Con el CLIC DERECHO mantenido miras por la mira.", "Fire with the LEFT CLICK: the belt holds 100 bullets. With the RIGHT CLICK held you look through the sight." },
            { "Clic izquierdo mantenido.", "Left click held." },
            { "Q → TORRETA FIJA → SALIR", "Q → FIXED TURRET → LEAVE" },
            { "Mantén [Q] otra vez: estando en la torreta el radial ofrece SALIR DE LA TORRETA. Elígela (vuelves a tu arma y a tu lugar).", "Hold [Q] again: while on the turret the radial offers LEAVE THE TURRET. Pick it (you go back to your weapon and your spot)." },
            { "TORRETA FIJA; SALIR DE LA TORRETA es la segunda opción.", "FIXED TURRET; LEAVE THE TURRET is the second option." },
            { "MODO DIOS", "GOD MODE" },
            { "F4: activa el modo dios", "F4: turns on god mode" },
            { "Aprieta [F4]: NADIE de tu bando recibe daño (ni tú, ni tus aliados, ni tu tanque). Abajo aparece el cartel dorado. Sirve para probar y para practicar.", "Press [F4]: NOBODY on your side takes damage (not you, your allies or your tank). A gold sign shows at the bottom. Handy for testing and practice." },
            { "Tecla F4, arriba del teclado.", "F4 key, at the top of the keyboard." },
            { "F4 otra vez: lo apagas", "F4 again: you turn it off" },
            { "Aprieta [F4] de nuevo para apagarlo y volver al daño normal.", "Press [F4] again to turn it off and go back to normal damage." },
            { "Tecla F4.", "F4 key." },
            { "ENTRAR AL TANQUE (RADIAL)", "ENTER THE TANK (RADIAL)" },
            { "Camina hasta el tanque (columna naranja)", "Walk to the tank (orange column)" },
            { "Camina hasta el TANQUE marcado con la columna naranja (W A S D).", "Walk to the TANK marked with the orange column (W A S D)." },
            { "Está al norte, al final del camino de tierra.", "It is to the north, at the end of the dirt road." },
            { "Q → TANQUE → SUBIRME YO", "Q → TANK → GET IN MYSELF" },
            { "Estás cerca. MIRA al tanque y mantén [Q]: TANQUE aparece en dorado; elige SUBIRME YO (la cuarta opción). (En este paso [E] está desactivado para que practiques el radial.)", "You are close. LOOK at the tank and hold [Q]: TANK shows in gold; pick GET IN MYSELF (the fourth option). (In this step [E] is disabled so you practice the radial.)" },
            { "Apunta al tanque antes de mantener Q. Hay que estar a menos de 7 m.", "Aim at the tank before holding Q. You must be within 7 m." },
            { "ALIADOS AL TANQUE (RADIAL)", "ALLIES TO THE TANK (RADIAL)" },
            { "Q → TANQUE → SUBIR TODOS", "Q → TANK → BOARD ALL" },
            { "Mantén [Q]: estando en el tanque, TANQUE aparece en dorado. Elige SUBIR TODOS: tus aliados corren al tanque.", "Hold [Q]: while in the tank, TANK shows in gold. Pick BOARD ALL: your allies run to the tank." },
            { "TANQUE (dorado); SUBIR TODOS es la primera opción.", "TANK (gold); BOARD ALL is the first option." },
            { "Espera a que suban los 2", "Wait for the 2 to board" },
            { "Tus aliados corren al tanque y se sientan. Espera a que estén adentro.", "Your allies run to the tank and sit down. Wait until they are inside." },
            { "Si uno está lejos tarda un poco: caminan hasta el tanque.", "If one is far away it takes a while: they walk to the tank." },
            { "CAMBIAR A LA TORRETA", "SWITCH TO THE TURRET" },
            { "Presiona 2: pasas al cañón", "Press 2: you move to the cannon" },
            { "Presiona [2]: pasas al CAÑÓN. Si el puesto está ocupado, INTERCAMBIAS con quien lo ocupa.", "Press [2]: you move to the CANNON. If the post is taken, you SWAP with whoever is in it." },
            { "1 conductor · 2 cañón · 3 metralleta · 4 pasajero.", "1 driver · 2 cannon · 3 machine gun · 4 passenger." },
            { "MIRA DEL CAÑÓN Y LA METRALLETA", "CANNON AND MACHINE GUN SIGHT" },
            { "Clic derecho: miras por la mira del cañón", "Right click: you look through the cannon sight" },
            { "Con el CLIC DERECHO mantenido miras por el PERISCOPIO del cañón: ventana rectangular con escala de distancia y escalera de elevación (no es la mira de a pie). El cañón gira lento hacia donde apuntas.", "With the RIGHT CLICK held you look through the cannon PERISCOPE: a rectangular window with a range scale and an elevation ladder (not the on-foot sight). The cannon turns slowly toward where you aim." },
            { "Mantén el botón derecho estando en el asiento del cañón [2].", "Hold the right button while in the cannon seat [2]." },
            { "[3] la metralleta: mirilla normal", "[3] the machine gun: normal crosshair" },
            { "Suelta, aprieta [3]: la METRALLETA va en el puesto alto del tanque y usa la MIRILLA NORMAL, igual que las torretas fijas (sin zoom ni periscopio). Apunta con el mouse y mantén el CLIC IZQUIERDO para ráfagas.", "Release, press [3]: the MACHINE GUN sits in the tank's high seat and uses the NORMAL CROSSHAIR, just like fixed turrets (no zoom or periscope). Aim with the mouse and hold the LEFT CLICK for bursts." },
            { "El [3] cambia de asiento; la metralleta no lleva mira óptica.", "[3] changes seat; the machine gun has no optical sight." },
            { "Suelta y vuelve al cañón [2]", "Release and go back to the cannon [2]" },
            { "Suelta el clic derecho y aprieta [2]: la cámara vuelve a la tercera persona.", "Release the right click and press [2]: the camera goes back to third person." },
            { "Suelta el botón derecho y aprieta 2.", "Release the right button and press 2." },
            { "AVANZAR Y DISPARAR", "ADVANCE AND FIRE" },
            { "Q → TANQUE → TANQUE ALLÍ: avanza", "Q → TANK → TANK THERE: advance" },
            { "Mira al SUELO, adelante en el camino. Mantén [Q], elige TANQUE y sigue hasta TANQUE ALLÍ: un aliado conduce hasta ahí.", "Look at the GROUND, ahead on the road. Hold [Q], pick TANK and keep going to TANK THERE: an ally drives there." },
            { "Baja la mira hasta ver el suelo delante del tanque. TANQUE ALLÍ es la tercera opción. El tanque APLASTA los obstáculos y los enemigos que se le cruzan.", "Lower the aim until you see the ground ahead of the tank. TANK THERE is the third option. The tank CRUSHES obstacles and enemies in its way." },
            { "Dispara el cañón (clic izquierdo)", "Fire the cannon (left click)" },
            { "¡Vienen enemigos! Apunta el cañón con el mouse y dispara con el CLIC IZQUIERDO.", "Enemies are coming! Aim the cannon with the mouse and fire with the LEFT CLICK." },
            { "Mueve el mouse para apuntar el cañón hacia los soldados rojos y haz clic izquierdo.", "Move the mouse to aim the cannon at the red soldiers and left click." },
            { "Derriba a los enemigos que se acercan", "Take down the approaching enemies" },
            { "Sigue disparando: hay que derribar a 3 enemigos. (La metralleta de un aliado también ayuda.)", "Keep firing: you must take down 3 enemies. (An ally's machine gun helps too.)" },
            { "Apunta el cañón a los soldados rojos que se acercan y dispara.", "Aim the cannon at the approaching red soldiers and fire." },
            { "¡ENEMIGOS AL FRENTE!", "ENEMIES AHEAD!" },
            { "LLEGAR AL FINAL", "REACH THE END" },
            { "Llega a la meta dorada", "Reach the golden goal" },
            { "Sigue mandando el tanque con [Q] → TANQUE → TANQUE ALLÍ hasta la META DORADA, al final del camino.", "Keep sending the tank with [Q] → TANK → TANK THERE to the GOLDEN GOAL at the end of the road." },
            { "Apunta al suelo, cerca de la baliza dorada, y usa el radial.", "Aim at the ground near the golden beacon and use the radial." },
            { "BAJAR DEL TANQUE (RADIAL)", "GET OUT OF THE TANK (RADIAL)" },
            { "Q → TANQUE → BAJAR TODOS", "Q → TANK → DISMOUNT ALL" },
            { "Llegaste. Mantén [Q]: TANQUE aparece en dorado. Elige BAJAR TODOS (la segunda opción): tus aliados bajan del tanque (tú te quedas).", "You made it. Hold [Q]: TANK shows in gold. Pick DISMOUNT ALL (the second option): your allies get out of the tank (you stay)." },
            { "TANQUE (dorado); BAJAR TODOS es la segunda opción.", "TANK (gold); DISMOUNT ALL is the second option." },
            { "Los aliados bajan", "The allies get out" },
            { "Espera a que los 2 aliados salgan del tanque.", "Wait for the 2 allies to leave the tank." },
            { "Tardan un instante en bajar.", "They take a moment to get out." },
            { "Q → TANQUE → BAJARME YO", "Q → TANK → GET OUT MYSELF" },
            { "Ahora tú: mantén [Q], TANQUE y BAJARME YO (la última opción). (En este paso [E] está desactivado para que practiques el radial.)", "Now you: hold [Q], TANK and GET OUT MYSELF (the last option). (In this step [E] is disabled so you practice the radial.)" },
            { "TANQUE (dorado); BAJARME YO es la última opción.", "TANK (gold); GET OUT MYSELF is the last option." },
            { "¡TUTORIAL COMPLETADO!", "TUTORIAL COMPLETE!" },
            { "MURO · DEMOLER", "WALL · DEMOLISH" },
            { "REFUERZOS ENEMIGOS", "ENEMY REINFORCEMENTS" },
            { "¡REFUERZOS!", "REINFORCEMENTS!" },
            { "Muy bien. Sigamos...", "Well done. Let us go on..." },
            { "PISTA: ", "HINT: " },
            { "[F8] SALTAR PASO", "[F8] SKIP STEP" },
            { "[ESPACIO / CLIC] SIGUIENTE", "[SPACE / CLICK] NEXT" },
            { "Paso completo", "Step complete" },
            { "justo ENFRENTE ^", "right AHEAD ^" },
            { "a tu ESPALDA (gira) vv", "BEHIND you (turn) vv" },
            { "a tu DERECHA >>", "to your RIGHT >>" },
            { "a tu IZQUIERDA <<", "to your LEFT <<" },
            { "REFUERZOS ENEMIGOS EN EL CAMINO DE VUELTA", "ENEMY REINFORCEMENTS ON THE WAY BACK" },
            { "¡UNA HORDA TE PERSIGUE! ¡AL HELICOPTERO!", "A HORDE IS CHASING YOU! TO THE HELICOPTER!" },
            { "¡AGUANTASTE! UN CIVIL PIDE AYUDA: ROMPE EL CERCO Y SACALO", "YOU HELD ON! A CIVILIAN NEEDS HELP: BREAK THE SIEGE AND GET HIM OUT" },
            { "VOLVE AL CENTRO: EL TEMPORIZADOR ESTA DETENIDO", "GO BACK TO THE CENTER: THE TIMER IS STOPPED" },
            { "EL CIVIL MURIO", "THE CIVILIAN DIED" },
            { "¡CIVIL RESCATADO! LLEVALO AL HELICOPTERO (PUNTO DE ORIGEN)", "CIVILIAN RESCUED! TAKE HIM TO THE HELICOPTER (STARTING POINT)" },
            { "EL CIVIL SE QUEDO ATRAS: VOLVE POR EL", "THE CIVILIAN WAS LEFT BEHIND: GO BACK FOR HIM" },
            { "PERDISTE AL CIVIL", "YOU LOST THE CIVILIAN" },
            { "TODA LA ESCUADRA CAYO", "THE ENTIRE SQUAD FELL" },
            { "OBJETIVO 1/4 · INFILTRAR", "OBJECTIVE 1/4 · INFILTRATE" },
            { "OBJETIVO 2/4 · RESISTIR EN EL CENTRO", "OBJECTIVE 2/4 · HOLD THE CENTER" },
            { "VOLVE AL CENTRO: el temporizador esta detenido", "Go back to the center: the timer is stopped" },
            { "OBJETIVO 3/4 · RESCATAR AL CIVIL", "OBJECTIVE 3/4 · RESCUE THE CIVILIAN" },
            { "OBJETIVO 4/4 · ESCAPAR EN EL HELICOPTERO", "OBJECTIVE 4/4 · ESCAPE BY HELICOPTER" },
            { "Ya sabes moverte, disparar, dar órdenes y manejar el tanque.", "You now know how to move, shoot, give orders and drive the tank." },
            { "REPETIR TUTORIAL", "REPEAT TUTORIAL" },
            { "VOLVER AL MENÚ", "BACK TO MENU" },
            { "MISION CUMPLIDA", "MISSION ACCOMPLISHED" },
            { "1 · helipuerto", "1 · helipad" },
            { "2 · despegue", "2 · takeoff" },
            { "3 · la horda", "3 · the horde" },
            { "MUERTO", "DEAD" },
            { "VUELVE AL OBJETIVO", "RETURN TO OBJECTIVE" }
        };
    }
}
